### ISSUE TITLE
关于 easyconnect 长时间不用自动断开连接

### ISSUE THREAD

**Issue by Xbai-hang** [tangruize/NJU-EasyConnect-Script#1]
请问有没有什么策略可以去改变这个，期望是24小时连接

**Comment by tangruize** [comment]
我没有试过这么长时间连接，出现的原因不太清楚，看起来这是easyconnect本身的现象，而不是脚本的问题？我遇到过网络断开，图标会变成灰色的情况，恢复网络后它自动恢复了连接，而此时它并没有修改路由表，脚本优化的路由表仍然可用。

**Comment by tangruize** [comment]
可以开一个后台进程检测EasyConnect是否保持连接，比如`curl p.nju.edu.cn`，要是断了重启服务？
