### ISSUE TITLE
WSL2 下使用 EasyConnect 的问题

### ISSUE THREAD

**Issue by Martin7-1** [tangruize/NJU-EasyConnect-Script#3]
你好！首先我想要感谢你的这个项目。我现在在 Windows 的 WSL2 下想要使用 EasyConnect 连接校园网，我的环境是 Ubuntu 22.04。下面是我的 `cat /proc/version` 的输出：

```
Linux version 5.15.167.4-microsoft-standard-WSL2 (root@f9c826d3017f) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37)
```

我在使用  `bash start-easyconnect-wsl.sh` 遇到几个问题：

1. 我的 EasyConnect 是装在 Windows 下的版本，这是正确的吗？还是说我需要装 Linux 下的版本呢？
2. 我在运行的时候，在 wait 60s 的时候遇到了下面的输出：

```
Wait EasyConnect ... 60sUsage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
59sUsage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
58sUsage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
57sUsage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
56sUsage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
55sUsage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
54sUsage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
53sUsage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
52sUsage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
51sUsage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
50sUsage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
49sUsage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
48sUsage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
47sUsage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
46sUsage: grep [OPTION]... PATTERNS [FILE]...
```

请问一下这是 grep 命令的什么问题呢？十分感谢！

**Comment by tangruize** [comment]
你好，感谢使用！

你需要用的是windows版，https://github.com/tangruize/NJU-EasyConnect-Script/tree/master/Windows

Easy connect需要安装在Windows，点击create_shortcut创建快捷方式，在桌面找到快捷方式打开。easyconnect直接改的路由表，所以wsl2里也是能访问校园网的。

**Comment by Martin7-1** [comment]
感谢！意思是如果我不需要更改路由规则的话，就不需要这个仓库的任何操作就可以在 wsl2 里使用对吧？

因为我现在连接了之后在 wsl2 中使用 ping 或者 curl 校园网内的一个 ip 貌似都是访问不到的，但是在 windows 通过浏览器网页是可以访问的。

**Comment by tangruize** [comment]
> 意思是如果我不需要更改路由规则的话，就不需要这个仓库的任何操作就可以在 wsl2 里使用对吧？

如果不需要更改路由规则的话，不需要这个仓库的任何操作就可以使用。但是EasyConnect会将所有的地址都路由到VPN，使得访问非校园网也会很慢。这个项目的脚本就是优化路由规则，让不需要走VPN的IP不走VPN.

> 因为我现在连接了之后在 wsl2 中使用 ping 或者 curl 校园网内的一个 ip 貌似都是访问不到的

这个倒是比较奇怪，我不太清楚原因，我试了访问校园网的非公网IP是可以的。

**Comment by Martin7-1** [comment]
感谢！我把内网 ip 加到 `start-easyconnect-win.sh` subnet 中就可以访问了。
